# parameters:
#     env(DATABASE_PODPOINTAPI_URL): ''

# doctrine:
#     dbal:
#         url: '%env(resolve:DATABASE_PODPOINTAPI_URL)%'

#         # IMPORTANT: You MUST configure your server version,
#         # either here or in the DATABASE_URL env var (see .env file)
#         #server_version: '5.7'
#     orm:
#         auto_generate_proxy_classes: true
#         naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
#         auto_mapping: true
#         mappings:
#             App:
#                 is_bundle: false
#                 type: annotation
#                 dir: '%kernel.project_dir%/src/Entity'
#                 prefix: 'App\Entity'
#                 alias: App
parameters:
    env(DATABASE_PODPOINTAPI_URL): ''

doctrine:
    dbal:
        default_connection: podpointapi
        connections:
            podpointapi:
                url: '%env(DATABASE_PODPOINTAPI_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Podpointapi:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/Resources/config/doctrine/podpointapi'
                prefix: 'App\Entity'
                alias: Podpointapi
